import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
    	String OrderDetails = "============= Order details =============\\n";
    	String PromotionFoodCode = null;
    	int Promotion1Discount = 0;
    	int Promotion2Discount = 0;
        int Promotion1Sum = 0;
        int Promotion2Sum = 0;
    	//int OrderWODiscount = 0;
        int subtotal = 0;
    	int OrderTotal = 0;
        int FinalTotal = 0;
    	List<String> PromotionList = salesPromotionRepository.findAll().get(1).getRelatedItems();
    	
    	for (String input : inputs) {
    		String[] SplitItem = input.split("\\s");
    		int ItemCost = 0;
    		String ItemID = SplitItem[0];
    		String ItemName = null;
    		int Quantity = Integer.parseInt(SplitItem[2]);
    		
    		for (Item item : itemRepository.findAll()) {
    			if (item.getId().equals(ItemID)) {
    				ItemName = item.getName();
    				ItemCost = (int) item.getPrice();
                    subtotal = ItemCost * Quantity;
                    OrderTotal = OrderTotal + subtotal;
    				break;
    			}
    		}
            
            OrderDetails = OrderDetails + ItemName + " x " + Quantity + " = " + subtotal + " yuan\n";
    		//OrderWODiscount += Quantity * ItemCost;
    		//OrderDetails += ItemName + " x " + Quantity + " = " + OrderWODiscount + "yuan\n";
    		
    		//if (OrderWODiscount >=30) {
    			//Promotion1Discount = 6;
    		//}
    		
    		if (PromotionList.contains(ItemID)) {
    			if (PromotionFoodCode==null) {
    				PromotionFoodCode = ItemName;
    			} else {
    				PromotionFoodCode =PromotionFoodCode + ", "+ ItemName;
                    System.out.println(PromotionFoodCode);
    			}
                Promotion1Discount = Promotion1Discount + ItemCost * Quantity /2;
                Promotion1Sum = OrderTotal - Promotion1Discount;
    			//Promotion2Discount += Quantity * ItemCost /2 ;
    		}
            
            if (OrderTotal >= 30) {
               Promotion2Discount = Promotion2Discount+ 6;
               Promotion2Sum = OrderTotal - 6;
            }
            
    		
    	}
    	
    	OrderDetails += "-----------------------------------\n";
    	if (Promotion1Discount ==0 && Promotion2Discount ==0) {
    		//OrderTotal = OrderWODiscount;
            FinalTotal = OrderTotal;
            OrderDetails = OrderDetails +  "Total：" + FinalTotal + " yuan\n" +
                    "===================================";
    	} else if (Promotion1Discount>Promotion2Discount) {
    		 OrderDetails = OrderDetails + "Promotion used:\n" + "Half price for certain dishes (" + PromotionFoodCode + ")，saving 13 yuan\n" +
                    "-----------------------------------\n" +
                    "Total：" + Promotion1Sum + " yuan\n" +
                    "===================================";
    		//OrderTotal = OrderWODiscount - Promotion2Discount;
    	} else {
    		OrderDetails = OrderDetails + "Promotion used:\n" + "满30减6 yuan，saving 6 yuan\n" +
                    "-----------------------------------\n" +
                    "Total：" + Promotion2Sum + " yuan\n" +
                    "===================================";
    		//OrderTotal = OrderWODiscount - Promotion1Discount;
    	}
    	
    	//OrderDetails += "Total: " + OrderTotal +" yuan\n===================================";

        return OrderDetails;
    }
}
